# air.toml

root = "."
tmp_dir = "tmp"
testdata_dir = "testdata"

[build]
bin = "tmp/main"
cmd = "go build -o tmp/main ./cmd/server"
delay = 1000
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["assets", "tmp", "vendor", "testdata"]
exclude_regex = ["_test.go"]
log = "build-errors.log"
kill_delay = "0s"
rerun = false
rerun_delay = 500
stop_on_error = false

[color]
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
main_only = false
silent = false
time = false

[misc]
clean_on_exit = true

[proxy]
enabled = false

[screen]
clear_on_rebuild = true
keep_scroll = true
